### ISSUE TITLE
Add support for common terminals

### ISSUE THREAD

**Issue by vihu** [sam4llis/nvim-tundra#4]
It would be nice to export ansi/bright colors for some commonly used terminals like kitty, iterm and wezterm.

**Comment by sam4llis** [comment]
I’ll aim to upload some configurations this weekend for iTerm, WezTerm, etc. Thanks for bringing this to my attention :)

**Comment by sam4llis** [comment]
Commit 3cdc9d1 in the `dev` branch adds iTerm-2 ANSI support.

**Comment by vihu** [comment]
> Commit [3cdc9d1](https://github.com/sam4llis/nvim-tundra/commit/3cdc9d1c1c933bea478dcbf659271607cc5f7bca) in the `dev` branch adds iTerm-2 ANSI support.

This looks good!

I would suggest opening a PR over https://github.com/mbadolato/iTerm2-Color-Schemes for maximum compatibility purposes. I believe wezterm (and maybe kitty) can both benefit if the colorscheme for iterm existed in that repository.

Furthermore, you'd not have to maintain multiple terminal schemes within this repo :)

Reference:
https://github.com/wez/wezterm/pull/2221#issuecomment-1174332521
https://github.com/catppuccin/wezterm/issues/6

**Comment by sam4llis** [comment]
Great, I’ll likely have a closer look into this at the weekend :)

**Comment by sam4llis** [comment]
Commit 825ebb7 in the `dev` branch adds wezterm ANSI support.

**Comment by vihu** [comment]
> Commit [825ebb7](https://github.com/sam4llis/nvim-tundra/commit/825ebb7bb56a466db95f326faf894f73462919cc) in the `dev` branch adds wezterm ANSI support.

Just a suggestion, maybe instead of having to configure using the colors table, add something like `tundra.toml` to an `extras/wezterm` directory instead?

For example, `tundra.toml` could look like this:

```toml
# Tundra

[colors]
foreground = "#D1D5DB"
background = "#111827"

cursor_fg = "#111827"
cursor_bg = "#D1D5DB"
cursor_border = "#111827"

selection_fg = "#DDD6FE"
selection_bg = "#374151"

scrollbar_thumb = "#6B7280"
split = "#6B7280"

ansi = [ "#6B7280", "#FCA5A5", "#B1E3AD", "#FBC19D", "#BAE6FD", "#957FB8", "#DDD6FE", "#A5F3FC" ]
brights = [ "#6B7280", "#FCA5A5", "#B1E3AD", "#FBC19D", "#BAE6FD", "#938AA9", "#DDD6FE", "#A5F3FC" ]

[metadata]
author = "Sam Ellis"
name = "Tundra"
```

I can confirm that this works just fine with wezterm :)
